### ISSUE TITLE
Errors in Running on ArcGIS 10.5.1

### ISSUE THREAD

**Issue by clkling** [james-roden/arcgis-swath-profile#1]
Errors:

000622: Failed to execute (Rotate).Parameters are not valid
000628: Cannot set input into parameter angle

Results in failure to execute for entire process

**Comment by james-roden** [comment]
Hello,

I am unable to recreate the error. 

Can you confirm you are using a single polyline that is projected in a 2D coordinate system?

James

**Comment by clkling** [comment]
Confirmed, 2D coordinate system, and single polyline. Tried with multiple different iterations of the line, straight, curved, etc. Same error each time. Might be a version error in Arc.

**Comment by james-roden** [comment]
I have it working in 10.5.1.

If you're happy to send me the polyline and raster (size dependent) I'd be more than happy to take a look for you.

James

**Comment by james-roden** [comment]
Hey,

I made a couple of edits and now I can run this tool in 10.5.

Let me know if you're still having issues.

Closed.
